### PR TITLE
ajout de navbar-static-top

### PR DESCRIPTION
**Pull request by peinxy**
Pour essayer et voir

Answer me

### CODE REVIEW

**Comment by peinxy** [comment]
http://www.offradio.gr/

2015-07-23 11:39 GMT+00:00 MasterMind92 <notifications@github.com>:

> Merged #1 <https://github.com/MasterMind92/Essai1/pull/1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MasterMind92/Essai1/pull/1#event-363301491>.
>



-- 
*MAGASSOUBA Bo Lanciné*
*Technicien en développement informatique*

**Comment by peinxy** [comment]
Pein XY has invited you to use Quip.

To accept the invitation, click the following link:

  https://quip.com/v/dNcAUAvAS3s

Quip is the modern productivity suite that helps your team get work done faster. If you have any trouble accessing Quip, please visit the Help Center: https://quip.com/support/

Thanks,
The Quip Team

--------------------------------------------------
About: https://quip.com/about/
Support: https://quip.com/support/
Email Preferences: https://quip.com/account/email
Quip, 988 Market St., 7th Floor, San Francisco, CA 94102

**Comment by MasterMind92** [comment]
je suis aller voir et comme d'habitude c'est de la balle alors pour le
moment on va faire avec parce que le temps manque

2015-11-28 23:23 GMT+00:00 peinxy <notifications@github.com>:

**Comment by peinxy** [comment]
Pein XY is still waiting to collaborate with you on Quip.

To accept the invitation, click the following link:

  https://quip.com/v/dNcAUAvAS3s?tracking_code=dGzrYMwiMBF7

Quip is an insanely great productivity suite that combines chat, documents, task lists, and spreadsheets in one fast and easy to use application.: https://quip.com/support/

Thanks,
The Quip Team

--------------------------------------------------
About: https://quip.com/about/
Support: https://quip.com/support/
Email Preferences: https://quip.com/account/email
Quip, 988 Market St., 7th Floor, San Francisco, CA 94102

**Pull request merged**
